fail_fast: true

repos:
- repo: https://github.com/commitizen-tools/commitizen
  rev: v2.35.0
  hooks:
  - id: commitizen

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
    args: ['--maxkb=800']
  - id: check-json
  - id: check-xml

- repo: https://github.com/digitalpulp/pre-commit-php.git
  rev: 1.4.0
  hooks:
  - id: php-cs
    files: \.(php)$
    args: [-p --standard=PSR12 --ignore=migrations]

- repo: https://github.com/digitalpulp/pre-commit-php.git
  rev: 1.4.0
  hooks:
  - id: php-stan
    files: \.(php)$

- repo: https://gitlab.com/daverona/pre-commit/php
  rev: 0.6.0
  hooks:
  - id: phpmd
    args: [phpmd . html ruleset.xml]

- repo: https://github.com/digitalpulp/pre-commit-php.git
  rev: 1.4.0
  hooks:
  - id: php-unit

- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.32.2
  hooks:
  - id: markdownlint
